#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:18

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - node
        script:
          - npm install
    - parallel:
       - step:
           name: Code quality
           caches:
             - node
           script:
             - npx prettier --write "src/**"
       - step:
           name: Build
           script:
             - echo "Installing all packages..." 
             - npm install
             - echo "Building application..."
             - npm run build
       - step:
           name: Test
           script:
             - echo "Running Tests..." 
             - npm install
             - npm test
    - step:
        name: Package
        script:
          - git archive --format=tar.gz master -o ingame.tar.gz
        artifacts:
          - ingame.tar.gz
    - step:
        name: Deploy Preproduccion
        deployment: staging
        script:
          - npm install --global vercel
          - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          - vercel build --token=$VERCEL_TOKEN
          - vercel deploy --token=$VERCEL_TOKEN
        caches:
         - node
    - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - npm install --global vercel
          - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          - vercel build --token=$VERCEL_TOKEN
          - vercel deploy --token=$VERCEL_TOKEN
        caches:
         - node